### ISSUE TITLE
Minor doc change: incorrect email, no links except for insta, minor corrections

### ISSUE THREAD

**Issue by mkinney** [PCrnjak/PAROL6-Desktop-robot-arm#2]
Really impressive project. Docs remind me of Lego instructions. (which is a huge compliment)

1) Looks like the email is probably incorrect on page 3 of "Building instructions.pdf".

"● Or send us an email at: sourcerobots@gmai.com" (missing the "l" in gmail?)

2) Only the Instagram link is present (page 3). Did you want to add links to the other social media locations?

3) Page 4 "Some parts are not show" should probably be "Some parts are not shown"

4) Page 8, two "esthetic" should be "aesthetic"

5) On page 8, "If you are not using it you risk destroying your plastic parts" should probably be changed to something like, "If not torqued, then you risk destroying the plastic parts." (if that's what you were trying to state)

6) On page 8, "Attaching shaft couplers to motor shafts demands blue threadlocker." "demands" should probably be changed to "requires".

7) Imbus might be called an Allen or hex key wrench in the US

The rest looks like it is still a work in progress.

I'm assuming there will be more info on the board. (where to purchase, how to assemble, how to test with each of the steppers before assembly, etc.)

Hope this helps.

minor edit to this issue: If you supply the source docs for the pdf, PRs could be made directly.

**Comment by PCrnjak** [comment]
Wow, thank you! I didn't have enough time to grammar check and edit everything when I was writing that but over time I will fix them all.  About PCB there is a signup link here: https://forms.gle/XkSvStwnQxw1f8xL8
I will keep this open so I don't forget what needs to be done! Thank you!

**Comment by movefasta** [comment]
@PCrnjak  Also hackaday link forward to Faze4 page. Actually it should be https://hackaday.io/project/191860-parol6-desktop-robotic-arm

**Comment by PCrnjak** [comment]
Fixed that thank you!

**Comment by PCrnjak** [comment]
Fixed all thank you!
