### ISSUE TITLE
Where is the PCB

### ISSUE THREAD

**Issue by burak1000** [PCrnjak/PAROL6-Desktop-robot-arm#8]
I think this is a type of open source project ok great

1-  I want buy a PAROL6 arm but it is sold out.  
2- Ok  so I will print STL files and i will buy a control board ...   tadaaa control board sold out.
3 - No problem I can order a PCB and build myself this board  Supriseee There is no PCB files

Why do you relase this project please help me understand
 
 Also there is no original Drawing files (Fusion or Solid). If you dont want anyone to do this arm, please dont share STL files too. there is no difference between them.  because when we start this project and our days will gone and when a problem appear no way to fix it without original 3D files. I dont believe this STL files is perfect

If you want share an open sourced project please share it
Thanks

**Comment by PCrnjak** [comment]
Hey!
We are currently out of stock and will have next batch of PCBs available by the end of this month. About original files they are available in STEP format on our website for purchase. As it is stated on GitHub "Control software, GUI, and robots STL files are open-source."    If you have any more questions send us an email at info@source-robotics.com

**Comment by tcurdt** [comment]
@PCrnjak I think the point was that the PCBs are apparently not open source?

**Comment by burak1000** [comment]
> @PCrnjak I think the point was that the PCBs are apparently not open source?

you are absolutely right
